-- GENERATED by scripts/gen-scoring-sql-test.mjs from supabase/tests/fixtures/scoring-cases.json
-- Do not edit by hand.
begin;
select plan(40);

-- Seed: Priya, strong month
select is(public.safe_ratio(69, 75), 0.92::numeric, 'Seed: Priya, strong month: points %');
select is(public.safe_ratio(6, 6), 1::numeric, 'Seed: Priya, strong month: completion %');
select is(public.safe_ratio(5, 6), 0.8333::numeric, 'Seed: Priya, strong month: punctuality %');
select is(public.calc_assessment_score(public.safe_ratio(69, 75), public.safe_ratio(6, 6), public.safe_ratio(5, 6), 9.5, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb), 93.03::numeric, 'Seed: Priya, strong month: base score');
select is(public.calc_assessment_score(public.safe_ratio(69, 75), public.safe_ratio(6, 6), public.safe_ratio(5, 6), 9.5, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb) + 0, 93.03::numeric, 'Seed: Priya, strong month: total score');

-- Seed: Arjun, with bonus
select is(public.safe_ratio(81, 90), 0.9::numeric, 'Seed: Arjun, with bonus: points %');
select is(public.safe_ratio(6, 6), 1::numeric, 'Seed: Arjun, with bonus: completion %');
select is(public.safe_ratio(5, 6), 0.8333::numeric, 'Seed: Arjun, with bonus: punctuality %');
select is(public.calc_assessment_score(public.safe_ratio(81, 90), public.safe_ratio(6, 6), public.safe_ratio(5, 6), 8.5, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb), 90.83::numeric, 'Seed: Arjun, with bonus: base score');
select is(public.calc_assessment_score(public.safe_ratio(81, 90), public.safe_ratio(6, 6), public.safe_ratio(5, 6), 8.5, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb) + 2, 92.83::numeric, 'Seed: Arjun, with bonus: total score');

-- No tasks assigned: only discretionary counts
select is(public.safe_ratio(0, 0), 0::numeric, 'No tasks assigned: only discretionary counts: points %');
select is(public.safe_ratio(0, 0), 0::numeric, 'No tasks assigned: only discretionary counts: completion %');
select is(public.safe_ratio(0, 0), 0::numeric, 'No tasks assigned: only discretionary counts: punctuality %');
select is(public.calc_assessment_score(public.safe_ratio(0, 0), public.safe_ratio(0, 0), public.safe_ratio(0, 0), 5, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb), 5::numeric, 'No tasks assigned: only discretionary counts: base score');
select is(public.calc_assessment_score(public.safe_ratio(0, 0), public.safe_ratio(0, 0), public.safe_ratio(0, 0), 5, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb) + 0, 5::numeric, 'No tasks assigned: only discretionary counts: total score');

-- Nothing submitted: punctuality is 0
select is(public.safe_ratio(0, 40), 0::numeric, 'Nothing submitted: punctuality is 0: points %');
select is(public.safe_ratio(0, 4), 0::numeric, 'Nothing submitted: punctuality is 0: completion %');
select is(public.safe_ratio(0, 0), 0::numeric, 'Nothing submitted: punctuality is 0: punctuality %');
select is(public.calc_assessment_score(public.safe_ratio(0, 40), public.safe_ratio(0, 4), public.safe_ratio(0, 0), 10, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb), 10::numeric, 'Nothing submitted: punctuality is 0: base score');
select is(public.calc_assessment_score(public.safe_ratio(0, 40), public.safe_ratio(0, 4), public.safe_ratio(0, 0), 10, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb) + 0, 10::numeric, 'Nothing submitted: punctuality is 0: total score');

-- Repeating fractions round half-up at 4dp then 2dp
select is(public.safe_ratio(20, 30), 0.6667::numeric, 'Repeating fractions round half-up at 4dp then 2dp: points %');
select is(public.safe_ratio(1, 3), 0.3333::numeric, 'Repeating fractions round half-up at 4dp then 2dp: completion %');
select is(public.safe_ratio(2, 3), 0.6667::numeric, 'Repeating fractions round half-up at 4dp then 2dp: punctuality %');
select is(public.calc_assessment_score(public.safe_ratio(20, 30), public.safe_ratio(1, 3), public.safe_ratio(2, 3), 7.25, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb), 60.59::numeric, 'Repeating fractions round half-up at 4dp then 2dp: base score');
select is(public.calc_assessment_score(public.safe_ratio(20, 30), public.safe_ratio(1, 3), public.safe_ratio(2, 3), 7.25, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb) + 0, 60.59::numeric, 'Repeating fractions round half-up at 4dp then 2dp: total score');

-- Custom weights 50/25/15/10 with bonus
select is(public.safe_ratio(150, 175), 0.8571::numeric, 'Custom weights 50/25/15/10 with bonus: points %');
select is(public.safe_ratio(7, 8), 0.875::numeric, 'Custom weights 50/25/15/10 with bonus: completion %');
select is(public.safe_ratio(8, 8), 1::numeric, 'Custom weights 50/25/15/10 with bonus: punctuality %');
select is(public.calc_assessment_score(public.safe_ratio(150, 175), public.safe_ratio(7, 8), public.safe_ratio(8, 8), 8, '{"points":50,"completion":25,"punctuality":15,"discretionary":10}'::jsonb), 87.73::numeric, 'Custom weights 50/25/15/10 with bonus: base score');
select is(public.calc_assessment_score(public.safe_ratio(150, 175), public.safe_ratio(7, 8), public.safe_ratio(8, 8), 8, '{"points":50,"completion":25,"punctuality":15,"discretionary":10}'::jsonb) + 5, 92.73::numeric, 'Custom weights 50/25/15/10 with bonus: total score');

-- Exact half at the 4th decimal (1/32) rounds up
select is(public.safe_ratio(1, 32), 0.0313::numeric, 'Exact half at the 4th decimal (1/32) rounds up: points %');
select is(public.safe_ratio(1, 32), 0.0313::numeric, 'Exact half at the 4th decimal (1/32) rounds up: completion %');
select is(public.safe_ratio(0, 0), 0::numeric, 'Exact half at the 4th decimal (1/32) rounds up: punctuality %');
select is(public.calc_assessment_score(public.safe_ratio(1, 32), public.safe_ratio(1, 32), public.safe_ratio(0, 0), 0, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb), 2.5::numeric, 'Exact half at the 4th decimal (1/32) rounds up: base score');
select is(public.calc_assessment_score(public.safe_ratio(1, 32), public.safe_ratio(1, 32), public.safe_ratio(0, 0), 0, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb) + 0, 2.5::numeric, 'Exact half at the 4th decimal (1/32) rounds up: total score');

-- Perfect month
select is(public.safe_ratio(70, 70), 1::numeric, 'Perfect month: points %');
select is(public.safe_ratio(5, 5), 1::numeric, 'Perfect month: completion %');
select is(public.safe_ratio(5, 5), 1::numeric, 'Perfect month: punctuality %');
select is(public.calc_assessment_score(public.safe_ratio(70, 70), public.safe_ratio(5, 5), public.safe_ratio(5, 5), 10, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb), 100::numeric, 'Perfect month: base score');
select is(public.calc_assessment_score(public.safe_ratio(70, 70), public.safe_ratio(5, 5), public.safe_ratio(5, 5), 10, '{"points":60,"completion":20,"punctuality":10,"discretionary":10}'::jsonb) + 3, 103::numeric, 'Perfect month: total score');

select * from finish();
rollback;
