/**
 * Apps Script pasted once into a spreadsheet. On every edit to Status, Deliverable
 * link or Notes it stamps the exact edit time into column O (for last-write-wins)
 * and pings CrewBoard, which syncs that tab within seconds instead of waiting for
 * the 10-minute schedule. Each tab has its own token, which can only ask for that
 * tab to be synced.
 *
 * It runs as an installable trigger (UrlFetchApp needs permission), so the sheet's
 * owner runs `installCrewBoard` once and approves access.
 */
export function appsScriptFor(syncUrl: string, tokens: Record<string, string>): string {
  return `// CrewBoard — instant sync for this spreadsheet.
// 1. Extensions › Apps Script → replace everything with this → Save.
// 2. Pick "installCrewBoard" in the toolbar → Run → allow access (once, as the sheet owner).
// Generated by CrewBoard › Settings › Google Sheets. Generating again replaces these tokens.
var CREWBOARD_URL = ${JSON.stringify(syncUrl)};
var CREWBOARD_TABS = ${JSON.stringify(tokens, null, 2)};

function crewboardOnEdit(e) {
  var sheet = e.range.getSheet();
  var token = CREWBOARD_TABS[sheet.getName()];
  if (!token) return;
  var first = e.range.getColumn(), last = first + e.range.getNumColumns() - 1;
  if (last < 9 || first > 11 || e.range.getRow() < 2) return; // only Status, Deliverable link, Notes
  var stamp = new Date().toISOString();
  for (var r = 0; r < e.range.getNumRows(); r++) {
    sheet.getRange(e.range.getRow() + r, 15).setValue(stamp); // column O: exact edit time
  }
  SpreadsheetApp.flush();
  var res = UrlFetchApp.fetch(CREWBOARD_URL, {
    method: 'post',
    contentType: 'application/json',
    payload: JSON.stringify({ action: 'ping', token: token }),
    muteHttpExceptions: true,
  });
  if (res.getResponseCode() >= 300) console.warn('CrewBoard: ' + res.getContentText());
}

function installCrewBoard() {
  ScriptApp.getProjectTriggers().forEach(function (t) {
    if (t.getHandlerFunction() === 'crewboardOnEdit') ScriptApp.deleteTrigger(t);
  });
  ScriptApp.newTrigger('crewboardOnEdit').forSpreadsheet(SpreadsheetApp.getActive()).onEdit().create();
  SpreadsheetApp.getActive().toast('CrewBoard instant sync is on.');
}
`;
}
